module.exports.descriptors = [
    'Brillante',
    'Asomborso',
    'Poderoso',
    'Frondoso',
    'Cielo',
    'Agua',
    'Cabaña',
    'Vieja',
    'Desierto',
    'Valle',
    'Pantano',
    'Oceano',
    'Base Militar',
    'Arollo',
    'Las cascadas',
    'El silencio',
    'Casa del arbol',
]

module.exports.places = [
    'del abismo',
    'del condado',
    'del infierno ',
    'del cosmos',
    'de acapulco',
    'del corazón',
    'del volcán',
    'de fuego',
    'de la razón',
    'del santuario',
    'del río',
    'del venado',
    'del suspenso',
    'del sexo',
    'de la muerte',
    'con fortuna',
    'sin miedo al éxito',
    'de aristoteles',
    'del Kevin',
    'de las serpientes',
    'de Dios'
]
